version: '3.4'

services:
  node-starter:
    image: node-starter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
      - GIT_COMMIT_ID=debug
    ports:
      - 80:80
      - 9229:9229
    command: [ "node", "--inspect=0.0.0.0:9229", "app/app.cjs" ]
