name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  LATEST_TAG: ${{ vars.DOCKERHUB_USERNAME }}/node-starter:latest

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ env.LATEST_TAG }} for testing
        run: |
          docker build -t node-starter:latest .

      - name: Run ${{ env.LATEST_TAG }} for testing
        run: |
          docker run -p 80:80 --rm --detach ${{ env.LATEST_TAG }}

      - name: run tests
        uses: liatrio/github-actions/apprentice-action@v1.0.0

  push:
    runs-on: ubuntu-latest
    needs: build-and-test

    # Only push on main branch push, not PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.LATEST_TAG }}
          platforms: linux/amd64
