name: Build
on: [push]
env:
  TEST_TAG: cmumford/node-starter:test
  LATEST_TAG: cmumford/node-starter:latest
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.LATEST_TAG }}

    - name: Run ${{ env.LATEST_TAG }} for testing
      run: |
        docker run -p 80:80 --rm ${{ env.LATEST_TAG }}

    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
