name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PUSH_TAG: ${{ vars.DOCKERHUB_USERNAME }}/node-starter:latest
  TEST_TAG: node-starter:test

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run project tests
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ env.TEST_TAG }} for testing
        run: |
          docker build -t ${{ env.TEST_TAG }} --build-arg GIT_SHA1=${{ github.sha }} .

      - name: Run ${{ env.TEST_TAG }} for testing
        run: |
          docker run -p 80:80 --rm --detach ${{ env.TEST_TAG }}

      - name: run external tests
        uses: liatrio/github-actions/apprentice-action@v1.0.0

  push:
    runs-on: ubuntu-latest
    needs: build-and-test

    # Only push on main branch push, not PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.PUSH_TAG }}
          build-args: |
            GIT_SHA1=${{ github.sha }}
